# Generated by Django 5.0.2 on 2024-03-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branchcodes',
            fields=[
                ('Branch', models.CharField(max_length=100)),
                ('Code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('Abbrevation', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Gradepoints',
            fields=[
                ('Grade', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('Points', models.IntegerField()),
                ('Status', models.CharField(max_length=4)),
                ('Presence', models.CharField(max_length=7)),
            ],
        ),
    ]
