# Generated by Django 5.0.2 on 2024-03-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResultAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradepoints',
            name='Status',
            field=models.CharField(max_length=1),
        ),
    ]
